global:
  scrape_interval: 15s 
  evaluation_interval: 15s 
  
alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "remote_collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["167.99.242.146:9100"]